name: hardware Priority Queue Tests

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  simulate_suite:
    name: Functionality Verification
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/johnsony0/hwpq:latest
      options: --user root

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure environment tools are ready
        run: |
          if ! command -v iverilog &> /dev/null; then
            apt-get update && apt-get install -y iverilog grep
          fi
          iverilog -V | head -n 1
          chmod +x test/run_sim.sh test/run_all_sims.sh

      - name: Run test suite
        run: test/run_all_sims.sh

      - name: Upload all simulation logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-sim-logs
          path: build/
          if-no-files-found: ignore
